__default__:
    mem: 16000
    nodes: 1
    ntasks-per-node: 1
    cpus-per-task: 1
    time: "24:00:00"
    partition: all
    job-name: "{rule}"
    output: "{rule}.out"

getContextModel:
    mem: 16000
    ntasks-per-node: 1
    cpus-per-task: 2
    time: "04:00:00"

getConsistentModel:
    mem: 8000
    ntasks-per-node: 1
    cpus-per-task: 1
    time: "08:00:00"

calcFVA:
    mem: 16000
    ntasks-per-node: 1
    cpus-per-task: 1
    time: "08:00:00"

calcFVA_zeroBiomass:
    mem: 16000
    ntasks-per-node: 1
    cpus-per-task: 1
    time: "08:00:00"

samplingModel:
    mem: 16000
    ntasks-per-node: 1
    cpus-per-task: 16
    time: "08:00:00"

Analysis_calcFVAdist:
    mem: 32000
    cpus-per-task: 32
    time: "08:00:00"

Analysis_calcFVAjacc:
    mem: 32000
    cpus-per-task: 32
    time: "08:00:00"

Analysis_PERMANOVAonRxnDist:
    mem: 32000
    cpus-per-task: 32
    time: "08:00:00"

createLQMMmodels:
    mem: 32000
    cpus-per-task: 32
    time: "23:59:59"

calc_pFBA:
    mem: 8000
    cpus-per-task: 2
    time: "00:30:00"

summarize_pFBA:
    mem: 8000
    cpus-per-task: 2
    time: "00:30:00"

createLMMmodels:
    cpus-per-task: 8
    time: "01:00:00"

validateReactionsForExtraction:
    cpus-per-task: 1
    mem: 12000
    time: "8:00:00"

testCoreThresholds:
    cpus-per-task: 8
    mem: 16000
    time: "8:00:00"

